#!/bin/sh

show () {
    FILE=$(for last; do true; done; echo $last)
    READER="less"
    OPTION=""
    
    if [ $# -lt 1 ]
    then
	echo "usage: show [-lmnv]"
	echo "show file with small usefull options"
	return 1
    fi
    
    while getopts "mnlv" option
    do
	case "$option" in
	    l) FLAG_LESS="YES" ;;
	    m) FLAG_MORE="YES" ;;
	    n) FLAG_NUMB="YES" ;;
	    v) FLAG_VIEW="YES" ;;
	    h) echo "usage: show [-lmnv]"
	       echo "show file with small usefull options" ;;
	esac
    done
    
    if [ $FLAG_LESS ]
    then
	READER="less"
    fi
    
    if [ $FLAG_MORE ]
    then
	READER="more"
    fi
    
    if [ $FLAG_VIEW ]
    then
	READER="view"
    fi
    
    if [ $FLAG_NUMB ] && [ $READER == "less" ]
    then
	OPTION="-N"
    fi
    
    if [ $FLAG_NUMB ] && [ $READER == "" ]
    then
	OPTION=""
    fi
    
    cat "$FILE" \
	| sed -e "/^$/d" -e "/^#/d" \
	| $READER $OPTION
}
